### PR TITLE
[PROPOSAL] Use HTML <form> Tag in levels

### PR DESCRIPTION
**Pull request by jpJuni0r**
Will also provide a better UX as the user can now press the `ENTER`-key to submit restults

### CODE REVIEW

**Comment by geek-at** [comment]
Submit on enter is a nice idea but could be done via global js.

I think the "event.target" thing makes it a bit more complicated. I use this level to teach highschoolers about js and was very happy with the "el.value" part without jquery

**Comment by jpJuni0r** [comment]
So `$(event.target).find('name=pw]')[0].value` would be better?
Or also use a `#form [name=pw]` selector?

But I guess the way from my draft would be the one being used in at least more "professional areas"

**Comment by geek-at** [comment]
exactly, the problem is that this level is usually the first contact my students have to HTML/JS and I want it to be as simple as possible. The event thing is what's bothering me :/

**Comment by jpJuni0r** [comment]
So what would you suggest to do?

**Comment by geek-at** [comment]
keep it as simple as possible. Will add ENTER to submit global in /js/scripts.js

**Pull request closed without merging**
